import type { Metadata } from "next"
import "./globals.css"


export const metadata: Metadata = {
  title: "CPE Family 2026",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/osz8kmu.css"></link>
      </head>
      <body className="min-h-dvh w-screen">{children}</body>
    </html>
  );
}
