export const BankDict: { [key: string]: string } = {
	"002": "Bangkok Bank Public Company Limited (BBL)",
	"004": "Kasikornbank Public Company Limited (KBANK)",
	"006": "Krung Thai Bank Public Company Limited (KTB)",
	"008": "JPMorgan Chase Bank, Bangkok Branch (JPMC)",
	"009": "Oversea-Chinese Banking Corporation Ltd. (OCBC)",
	"010": "The Bank of Tokyo-Mitsubishi UFJ, Ltd",
	"011": "TMB Bank Public Company Limited (TTB)",
	"014": "Siam Commercial Bank Public Company Limited (SCB)",
	"017": "Citibank N.A. (CITI)",
	"018": "Sumitomo Mitsui Banking Corporation (SMBC)",
	"020": "Standard Chartered Bank (Thai) Public Company Limited (SCBT)",
	"022": "CIMB Thai Bank Public Company Limited (CIMB)",
	"023": "RHB Bank Berhad (RHB)",
	"024": "United Overseas Bank (Thai) PCL (UOBT)",
	"025": "Bank of Ayudhya Public Company Limited (BAY)",
	"026": "Mega International Commercial Bank Public Company Limited (MEGA ICBC)",
	"027": "Bank of America National Association (AMERICA)",
	"028": "Calyon",
	"029": "Indian Overseas Bank, Bangkok Branch (I.O.B.)",
	"030": "Government Saving Bank (GOV)",
	"031": "Hong Kong & Shanghai Corporation Limited (HSBC)",
	"032": "Deutsche Bank Aktiengesellschaft (DB)",
	"033": "Government Housing Bank (GHB)",
	"034": "Bank for Agriculture and Agricultural Cooperatives (AGRI)",
	"035": "Export-Import Bank of Thailand (EXIM)",
	"039": "Mizuho Corporate Bank Limited (MHCB)",
	"045": "BNPN Paribas, Bangkok (BNPP)",
	"052": "Bank of China Limited, Bangkok Branch (BOC)",
	"065": "Thanachart Bank Public Company",
	"066": "Islamic Bank of Thailand (ISBT)",
	"067": "Tisco Bank Public Company Limited (TISCO)",
	"069": "Kiatnakin Bank Public Company Limited (KK)",
	"070": "Industrial and Commercial Bank of China (THAI) Public Company Limited (ICBC)",
	"071": "The Thai Credit Retail Bank Public Company Limited (TCRB)",
	"073": "Land and Houses Bank Public Company Limited (LHBANK)",
	"079": "ANZ Bank (Thai) Public Company Limited (ANZ)",
	"080": "Sumitomo Mitsui Trust Bank (THAI) PCL. (SMTB)",
	"098": "Small and Medium Enterprise Development Bank of Thailand (SMEB)",
}
